package frames;

import entity.Empleado;
import entity.Empresa;
import java.util.ArrayList;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julan
 */
public class Regristro extends javax.swing.JFrame {

    private static Empresa empresa;
    private static ArrayList<Empresa> listaEmpresas = new ArrayList<Empresa>();
    public static DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Regristro
     */
    public Regristro() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jdpPanel1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jtfDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfSueldo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        jcbEmpresas = new javax.swing.JComboBox<>();
        jbGuardar = new javax.swing.JButton();
        jbMostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jdpPanel2 = new javax.swing.JDesktopPane();
        jLabel9 = new javax.swing.JLabel();
        jtfRazon = new javax.swing.JTextField();
        jtfCuit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jbCrearEmpresa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabla = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Empresa");

        jdpPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Documento");

        jtfDocumento.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");

        jtfNombre.setBackground(new java.awt.Color(255, 255, 255));

        jtfApellido.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Apellido");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Categoria");

        jtfSueldo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Sueldo");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Empresa");

        jcbCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "GERENTE", "JEFE", "ADMINISTRATIVO", "OPERARIO CALIFICADO", "AUXILIAR", "OPERARIO", "LIMPIEZA" }));

        jcbEmpresas.setBackground(new java.awt.Color(255, 255, 255));
        jcbEmpresas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbMostrar.setText("Mostrar Empleados");
        jbMostrar.setEnabled(false);
        jbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarActionPerformed(evt);
            }
        });

        jdpPanel1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jtfDocumento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jtfNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jtfApellido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jtfSueldo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jcbCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jcbEmpresas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jbGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel1.setLayer(jbMostrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPanel1Layout = new javax.swing.GroupLayout(jdpPanel1);
        jdpPanel1.setLayout(jdpPanel1Layout);
        jdpPanel1Layout.setHorizontalGroup(
            jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPanel1Layout.createSequentialGroup()
                .addGroup(jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdpPanel1Layout.createSequentialGroup()
                                .addGroup(jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfSueldo)
                    .addComponent(jtfApellido)
                    .addComponent(jtfNombre)
                    .addComponent(jtfDocumento)
                    .addComponent(jcbCategoria, 0, 184, Short.MAX_VALUE)
                    .addComponent(jcbEmpresas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbMostrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jdpPanel1Layout.setVerticalGroup(
            jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jdpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbMostrar))
                .addGap(26, 26, 26))
        );

        jLabel1.setText("Ingrese datos");

        jdpPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Razon Social");

        jtfRazon.setBackground(new java.awt.Color(255, 255, 255));
        jtfRazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRazonActionPerformed(evt);
            }
        });

        jtfCuit.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("CUIT");

        jbCrearEmpresa.setText("Crear Empresa");
        jbCrearEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearEmpresaActionPerformed(evt);
            }
        });

        jdpPanel2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel2.setLayer(jtfRazon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel2.setLayer(jtfCuit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel2.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPanel2.setLayer(jbCrearEmpresa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPanel2Layout = new javax.swing.GroupLayout(jdpPanel2);
        jdpPanel2.setLayout(jdpPanel2Layout);
        jdpPanel2Layout.setHorizontalGroup(
            jdpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPanel2Layout.createSequentialGroup()
                .addGroup(jdpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jdpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jdpPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(35, 35, 35)
                                .addComponent(jtfCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jdpPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(35, 35, 35)
                                .addComponent(jtfRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jdpPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jbCrearEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jdpPanel2Layout.setVerticalGroup(
            jdpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jdpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbCrearEmpresa)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel2.setText("Ingrese datos");

        jtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtTabla.setEnabled(false);
        jScrollPane1.setViewportView(jtTabla);

        jMenu1.setText("Empleado");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Empresa");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sueldo");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jdpPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdpPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdpPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jdpPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCrearEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearEmpresaActionPerformed
        String razonSocial = jtfRazon.getText();
        String strCuit = jtfCuit.getText();
        int cuit;
        if (razonSocial.isBlank() || strCuit.isBlank()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar todos los datos");
            return;
        }

        try {
            cuit = Integer.parseInt(strCuit);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al ingresar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Empresa e = new Empresa(razonSocial, cuit);
        listaEmpresas.add(e);
//       if (!(listaEmpresas.add(e))){
//           JOptionPane.showMessageDialog(this,"Esta empresa ya existe.","Error",JOptionPane.ERROR_MESSAGE);
//           return;
//      }
        jcbEmpresas.addItem(e.toString());
        jtfRazon.setText("");
        jtfCuit.setText("");
        jbGuardar.setEnabled(true);
        jbMostrar.setEnabled(true);
    }//GEN-LAST:event_jbCrearEmpresaActionPerformed

    private void jtfRazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRazonActionPerformed

    }//GEN-LAST:event_jtfRazonActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        String strDocumento = jtfDocumento.getText();
        String apellido = jtfApellido.getText();
        String nombre = jtfNombre.getText();
        String categoria = (String) jcbCategoria.getSelectedItem();
        String strSueldo = jtfSueldo.getText();
        String strEmpresa = (String) jcbEmpresas.getSelectedItem();
        int documento;
        double sueldo;
        Empresa empresaSelect = null;

        if (strDocumento.isBlank() || apellido.isBlank() || nombre.isBlank()
                || strSueldo.isBlank() || categoria == null || strEmpresa == null) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            documento = Integer.parseInt(strDocumento);
            sueldo = Double.parseDouble(strSueldo);
        } catch (NumberFormatException es) {
            JOptionPane.showMessageDialog(this, "Ingreso de datos incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (Empresa e : listaEmpresas) {
            if (e.GetRazonSocial().equals(strEmpresa)) {
                empresaSelect = e;
            }
        }
        if (empresaSelect == null) {
            JOptionPane.showMessageDialog(this, "No se ha encontrado la empresa", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Empleado nuevoEmpleado = new Empleado(documento, nombre, apellido, categoria, sueldo, empresaSelect);
        empresaSelect.agregarEmpleado(nuevoEmpleado);
        empresa = empresaSelect;
        limpiarCampos();
        jtTabla.setEnabled(true);
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarActionPerformed
        empresa.mostrarEmpleados();
    }//GEN-LAST:event_jbMostrarActionPerformed

    private void limpiarCampos() {
        jtfDocumento.setText("");
        jtfNombre.setText("");
        jtfApellido.setText("");
        jcbCategoria.setSelectedIndex(0);
        jtfSueldo.setText("");
        jcbEmpresas.setSelectedIndex(0);
    }

    private void armarCabecera() {
        model.addColumn("Empresa");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Documento");
        model.addColumn("Categoria");
        jtTabla.setModel(model);
        jtTabla.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regristro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regristro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regristro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regristro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regristro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCrearEmpresa;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbMostrar;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JComboBox<String> jcbEmpresas;
    private javax.swing.JDesktopPane jdpPanel1;
    private javax.swing.JDesktopPane jdpPanel2;
    private javax.swing.JTable jtTabla;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfCuit;
    private javax.swing.JTextField jtfDocumento;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfRazon;
    private javax.swing.JTextField jtfSueldo;
    // End of variables declaration//GEN-END:variables

}
